[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_unsubscribe_from_single_content_topic with id: 2024-12-04_11-44-47__aa0661a1-c620-471e-8a29-fb391ef9e3a4
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-47__aa0661a1-c620-471e-8a29-fb391ef9e3a4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.187.52
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['62390', '62391', '62392', '62393', '62394']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 62390:62390 -p 62391:62391 -p 62392:62392 -p 62393:62393 -p 62394:62394 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=62392 --rest-port=62390 --tcp-port=62391 --discv5-udp-port=62393 --rest-address=0.0.0.0 --nat=extip:172.18.187.52 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=d6e7c3bec5f57a4d05b352fdd1c6aa239a76bedc600b70e4e7f37bfb461a4f3c --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=62394 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.187.52 waku cce0bb713f9fc9ce9dc16e78f05121fd4348c76fc6416af5fa58c527a007508a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID cce0bb713f9f. Setting up logs at ./log/docker/node1_2024-12-04_11-44-47__aa0661a1-c620-471e-8a29-fb391ef9e3a4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 62390
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:62390/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:62390/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.187.52/tcp/62391/p2p/16Uiu2HAmJUstFyeB3Udi8zhnqsHYUNPFYDevnm4SayY6biqSgomo","/ip4/172.18.187.52/tcp/62392/ws/p2p/16Uiu2HAmJUstFyeB3Udi8zhnqsHYUNPFYDevnm4SayY6biqSgomo"],"enrUri":"enr:-L24QBnUaFUKkZpX1_NJA7PIo3W_bXXfIdqMLi_PVJRWlspeQrRuTr8GILd-ywLYEwxFmVAQW-vLVU9XjjAUmXOFov4CgmlkgnY0gmlwhKwSuzSKbXVsdGlhZGRyc5YACASsErs0BvO3AAoErBK7NAbzuN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDVo8AlZTcel266RXCCLy4xhIJ13n_DPReuZy-nhh4H4aDdGNwgvO3g3VkcILzuYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-47__aa0661a1-c620-471e-8a29-fb391ef9e3a4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.44.120
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['27763', '27764', '27765', '27766', '27767']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 27763:27763 -p 27764:27764 -p 27765:27765 -p 27766:27766 -p 27767:27767 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=27765 --rest-port=27763 --tcp-port=27764 --discv5-udp-port=27766 --rest-address=0.0.0.0 --nat=extip:172.18.44.120 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=9a7ddeccd5d65d2bfef1fed4fc667c18cf2cace25ccc9e91581ea367beb6fab9 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=27767 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QBnUaFUKkZpX1_NJA7PIo3W_bXXfIdqMLi_PVJRWlspeQrRuTr8GILd-ywLYEwxFmVAQW-vLVU9XjjAUmXOFov4CgmlkgnY0gmlwhKwSuzSKbXVsdGlhZGRyc5YACASsErs0BvO3AAoErBK7NAbzuN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDVo8AlZTcel266RXCCLy4xhIJ13n_DPReuZy-nhh4H4aDdGNwgvO3g3VkcILzuYV3YWt1MgU --filternode=/ip4/172.18.187.52/tcp/62391/p2p/16Uiu2HAmJUstFyeB3Udi8zhnqsHYUNPFYDevnm4SayY6biqSgomo
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.44.120 waku 0e0f1dafcc8329bc769d955ca8687164a07b3cda4cd787a872e28ef9bf0e5d32
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 0e0f1dafcc83. Setting up logs at ./log/docker/node2_2024-12-04_11-44-47__aa0661a1-c620-471e-8a29-fb391ef9e3a4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 27763
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27763/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27763/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.44.120/tcp/27764/p2p/16Uiu2HAmNhXPDmcghw94sZhPwCxy48tFzci5jC6arnXhJCknMdGT","/ip4/172.18.44.120/tcp/27765/ws/p2p/16Uiu2HAmNhXPDmcghw94sZhPwCxy48tFzci5jC6arnXhJCknMdGT"],"enrUri":"enr:-L24QH_uXP7h4mdDant_oLOtGjH9dbMBhXxBP_KFWNOldvFTCgBR2DQmIEGgY0qAdqlyLroIV0lZBB7MN9juF7N1iT0CgmlkgnY0gmlwhKwSLHiKbXVsdGlhZGRyc5YACASsEix4Bmx0AAoErBIseAZsdd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDlTsezpoKaqTUmrt4ejMMRfxdPd57VMz_5WMGFPEjrKCDdGNwgmx0g3VkcIJsdoV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27763/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.187.52/tcp/62391/p2p/16Uiu2HAmJUstFyeB3Udi8zhnqsHYUNPFYDevnm4SayY6biqSgomo"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:62390/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27763/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "843d48c7-3455-4063-a886-40334fc96857", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"843d48c7-3455-4063-a886-40334fc96857","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:62390/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27763/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1733312704013522176,"ephemeral":false}]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X DELETE "http://127.0.0.1:27763/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "1", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"1","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:62390/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27763/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[1m[31mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:27763/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto. Response content: b'Not subscribed to topic: /test/1/waku-filter/proto'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id cce0bb713f9f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 0e0f1dafcc83
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container cce0bb713f9f. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.