[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter with id: 2024-12-04_11-44-46__04f47bcd-7972-44ff-9138-33e47a702606
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.store:store.py:31 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__04f47bcd-7972-44ff-9138-33e47a702606__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.187.82
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['23022', '23023', '23024', '23025', '23026']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 23022:23022 -p 23023:23023 -p 23024:23024 -p 23025:23025 -p 23026:23026 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=23024 --rest-port=23022 --tcp-port=23023 --discv5-udp-port=23025 --rest-address=0.0.0.0 --nat=extip:172.18.187.82 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=8b3c5e31410feddfe3dc8fd079c7814cdb6d63f29eec7fdabd51fa6a4bb75b3e --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=23026 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.187.82 waku 6939eccd28c4c428a067285a7813caf654e753ef5d6b10b9d71aee4f8a288d72
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 6939eccd28c4. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__04f47bcd-7972-44ff-9138-33e47a702606__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 23022
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:23022/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:23022/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.187.82/tcp/23023/p2p/16Uiu2HAm5kikwPx6jYj46uxJeGyD3F57Yc7dqRivQZXNp2sE8D5b","/ip4/172.18.187.82/tcp/23024/ws/p2p/16Uiu2HAm5kikwPx6jYj46uxJeGyD3F57Yc7dqRivQZXNp2sE8D5b"],"enrUri":"enr:-L24QFcjFSI_ba_5k_v67-y_ham5xt3OZ2pfW3ZN1V2NGmG3LLwSR68PZbQb-zHr96ikwlNQZXiSUC8uy1ozHT1KmXICgmlkgnY0gmlwhKwSu1KKbXVsdGlhZGRyc5YACASsErtSBlnvAAoErBK7UgZZ8N0DgnJzhQADAQAAiXNlY3AyNTZrMaECmXYL0AcP2l0qzmtBH4MlC0QYpRgmsCzMyeGDtHZptaKDdGNwglnvg3VkcIJZ8YV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__04f47bcd-7972-44ff-9138-33e47a702606__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.135.244
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['6555', '6556', '6557', '6558', '6559']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 6555:6555 -p 6556:6556 -p 6557:6557 -p 6558:6558 -p 6559:6559 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=6557 --rest-port=6555 --tcp-port=6556 --discv5-udp-port=6558 --rest-address=0.0.0.0 --nat=extip:172.18.135.244 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=f9aa8ecfbd744fce88ddf07b9cb44aab1c21fdda32abf02cdebfdcd1a4bb6a73 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=6559 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QFcjFSI_ba_5k_v67-y_ham5xt3OZ2pfW3ZN1V2NGmG3LLwSR68PZbQb-zHr96ikwlNQZXiSUC8uy1ozHT1KmXICgmlkgnY0gmlwhKwSu1KKbXVsdGlhZGRyc5YACASsErtSBlnvAAoErBK7UgZZ8N0DgnJzhQADAQAAiXNlY3AyNTZrMaECmXYL0AcP2l0qzmtBH4MlC0QYpRgmsCzMyeGDtHZptaKDdGNwglnvg3VkcIJZ8YV3YWt1MgU --filternode=/ip4/172.18.187.82/tcp/23023/p2p/16Uiu2HAm5kikwPx6jYj46uxJeGyD3F57Yc7dqRivQZXNp2sE8D5b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.135.244 waku b54ac7f58ee85da6a81033c66f41962d679c4477c33cc6977b8ec6dab69c0053
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID b54ac7f58ee8. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__04f47bcd-7972-44ff-9138-33e47a702606__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 6555
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:6555/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:6555/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.135.244/tcp/6556/p2p/16Uiu2HAky392xhKuwBSxA57R4ffwKjTTyvWtDV8LnavejeF2BgTQ","/ip4/172.18.135.244/tcp/6557/ws/p2p/16Uiu2HAky392xhKuwBSxA57R4ffwKjTTyvWtDV8LnavejeF2BgTQ"],"enrUri":"enr:-L24QBhahbpleUukacI_8DyWRjU1_U2JoiogggX1s65ZoCqbergHvlbkTKwNYVFK98BddFX27lwUVOtJrh7c5Kx2tToCgmlkgnY0gmlwhKwSh_SKbXVsdGlhZGRyc5YACASsEof0BhmcAAoErBKH9AYZnd0DgnJzhQADAQAAiXNlY3AyNTZrMaECNaj61yQ4mo9UmcjdxI_JX9O_nutUXs0JFVZ3VkN5KxeDdGNwghmcg3VkcIIZnoV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:23022/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:6555/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "d1b78da3-2f90-4380-bf4c-fb43deafe5d3", "contentFilters": ["/test/1/waku-relay/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"d1b78da3-2f90-4380-bf4c-fb43deafe5d3","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:23022/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "UmVsYXkgd29ya3MhIQ==", "contentTopic": "/test/1/waku-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:6555/filter/v2/messages/%2Ftest%2F1%2Fwaku-relay%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"UmVsYXkgd29ya3MhIQ==","contentTopic":"/test/1/waku-relay/proto","version":0,"timestamp":1733312709569425408,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 6939eccd28c4
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id b54ac7f58ee8
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 6939eccd28c4. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.