[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_meta with id: 2024-12-04_11-44-46__2e4edb06-05ec-4753-b5f9-6a37bd8cf64c
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__2e4edb06-05ec-4753-b5f9-6a37bd8cf64c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.168.221
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['58634', '58635', '58636', '58637', '58638']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 58634:58634 -p 58635:58635 -p 58636:58636 -p 58637:58637 -p 58638:58638 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=58636 --rest-port=58634 --tcp-port=58635 --discv5-udp-port=58637 --rest-address=0.0.0.0 --nat=extip:172.18.168.221 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=71e2c9bee1fab588f3ebb8ab322bcf4ae8cbbd23e8c25b27afc8f897abbeba3b --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=58638 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.168.221 waku 478c0b1964c7195b51620699855b117d3b7018e282232e829e28aaf2d4d376d2
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 478c0b1964c7. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__2e4edb06-05ec-4753-b5f9-6a37bd8cf64c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 58634
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58634/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58634/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.168.221/tcp/58635/p2p/16Uiu2HAmQKqSsc3rXc7wT8BeFA1D4o3vnYxFyYTdJCmxEi47jqfW","/ip4/172.18.168.221/tcp/58636/ws/p2p/16Uiu2HAmQKqSsc3rXc7wT8BeFA1D4o3vnYxFyYTdJCmxEi47jqfW"],"enrUri":"enr:-L24QFUeAlVREGx0qRbQ3G-X9zPC1fGOZYAu-QbH8XwxafqgKboi9EKUNyqhvafFCBr_b0aCaP2b1sgV3toIuPxGk7oCgmlkgnY0gmlwhKwSqN2KbXVsdGlhZGRyc5YACASsEqjdBuULAAoErBKo3QblDN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDrWQj6A7pCw2c3sVwYWmNVj6WwS5RiRIjGRRyqZJrhQmDdGNwguULg3VkcILlDYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-46__2e4edb06-05ec-4753-b5f9-6a37bd8cf64c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.38.203
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['12770', '12771', '12772', '12773', '12774']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 12770:12770 -p 12771:12771 -p 12772:12772 -p 12773:12773 -p 12774:12774 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=12772 --rest-port=12770 --tcp-port=12771 --discv5-udp-port=12773 --rest-address=0.0.0.0 --nat=extip:172.18.38.203 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bbb26df4f02faa5fce4287d4f00b84673aeab5a673db987accfd9df9c4139fe1 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=12774 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QFUeAlVREGx0qRbQ3G-X9zPC1fGOZYAu-QbH8XwxafqgKboi9EKUNyqhvafFCBr_b0aCaP2b1sgV3toIuPxGk7oCgmlkgnY0gmlwhKwSqN2KbXVsdGlhZGRyc5YACASsEqjdBuULAAoErBKo3QblDN0DgnJzhQADAQAAiXNlY3AyNTZrMaEDrWQj6A7pCw2c3sVwYWmNVj6WwS5RiRIjGRRyqZJrhQmDdGNwguULg3VkcILlDYV3YWt1MgU --filternode=/ip4/172.18.168.221/tcp/58635/p2p/16Uiu2HAmQKqSsc3rXc7wT8BeFA1D4o3vnYxFyYTdJCmxEi47jqfW
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.38.203 waku 9bd7982a0f6580d4bc5dc68d1bc6e5ad6a27ccc67b94085b44056b8fcd98cb1c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 9bd7982a0f65. Setting up logs at ./log/docker/node2_2024-12-04_11-44-46__2e4edb06-05ec-4753-b5f9-6a37bd8cf64c__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 12770
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12770/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12770/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.38.203/tcp/12771/p2p/16Uiu2HAmFyv9nBrYdAEQouDwtitCiZ7fT9qzjLP73ckzt2xLkVvR","/ip4/172.18.38.203/tcp/12772/ws/p2p/16Uiu2HAmFyv9nBrYdAEQouDwtitCiZ7fT9qzjLP73ckzt2xLkVvR"],"enrUri":"enr:-L24QM5QkH5u7TIZNWqf4N3HqbHmdBf0j_MgbT_wTDsCiG08HraZuqFxAbzjcdLtEK_rFryU6c-NLT2n0nEnjcrx4FECgmlkgnY0gmlwhKwSJsuKbXVsdGlhZGRyc5YACASsEibLBjHjAAoErBImywYx5N0DgnJzhQADAQAAiXNlY3AyNTZrMaEDMWxZVOHTzEbtNKVUj8YeRHZZUhhGTHOmc9MAnDgh7xKDdGNwgjHjg3VkcIIx5YV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12770/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.168.221/tcp/58635/p2p/16Uiu2HAmQKqSsc3rXc7wT8BeFA1D4o3vnYxFyYTdJCmxEi47jqfW"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58634/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12770/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "5840e5c4-1e3b-496f-b649-af9eb00e7a69", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"5840e5c4-1e3b-496f-b649-af9eb00e7a69","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58634/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "meta": "RmlsdGVyIHdvcmtzISE="}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12770/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1733312710853340160,"meta":"RmlsdGVyIHdvcmtzISE=","ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 478c0b1964c7
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 9bd7982a0f65
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 478c0b1964c7. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.