[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_ephemeral with id: 2024-12-04_11-44-46__b8e58e4d-8a9f-4015-a11f-13b4a7d16496
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__b8e58e4d-8a9f-4015-a11f-13b4a7d16496__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.47.141
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['16438', '16439', '16440', '16441', '16442']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 16438:16438 -p 16439:16439 -p 16440:16440 -p 16441:16441 -p 16442:16442 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=16440 --rest-port=16438 --tcp-port=16439 --discv5-udp-port=16441 --rest-address=0.0.0.0 --nat=extip:172.18.47.141 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=c5faedc3eeb90cf6d0db23a0a1d6cd47f6ad7b7cb2edab4bebfdbf22a70e1f2e --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=16442 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.47.141 waku c4d259a7f113cd2b647c4af670bb700d852f139cdb1cd0627703cc18efecf23b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID c4d259a7f113. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__b8e58e4d-8a9f-4015-a11f-13b4a7d16496__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 16438
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:16438/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:16438/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.47.141/tcp/16439/p2p/16Uiu2HAmUL9pMnARBy3dPdwXsam9hDZBAbjJbMS2LWA6d2fNQw2J","/ip4/172.18.47.141/tcp/16440/ws/p2p/16Uiu2HAmUL9pMnARBy3dPdwXsam9hDZBAbjJbMS2LWA6d2fNQw2J"],"enrUri":"enr:-L24QEUMDVT_ueOz8-19G_cMGn7HdhzeKFsG_wkpj-CvUh0qAGmzDqgmXd-LeMM-_LaRM2k86fVadfLOXelNv7CQwQECgmlkgnY0gmlwhKwSL42KbXVsdGlhZGRyc5YACASsEi-NBkA3AAoErBIvjQZAON0DgnJzhQADAQAAiXNlY3AyNTZrMaED6Oeo1IGkFHaiCJwMMoYvMLnk-kssqhU5RMsA3lO3MsuDdGNwgkA3g3VkcIJAOYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-46__b8e58e4d-8a9f-4015-a11f-13b4a7d16496__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.9.171
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['43952', '43953', '43954', '43955', '43956']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 43952:43952 -p 43953:43953 -p 43954:43954 -p 43955:43955 -p 43956:43956 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=43954 --rest-port=43952 --tcp-port=43953 --discv5-udp-port=43955 --rest-address=0.0.0.0 --nat=extip:172.18.9.171 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=dc9a5e7b6fbe6d425da6e7eae0fffcb4af45acaa4bf2868e4c52adefd9f34c3d --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=43956 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QEUMDVT_ueOz8-19G_cMGn7HdhzeKFsG_wkpj-CvUh0qAGmzDqgmXd-LeMM-_LaRM2k86fVadfLOXelNv7CQwQECgmlkgnY0gmlwhKwSL42KbXVsdGlhZGRyc5YACASsEi-NBkA3AAoErBIvjQZAON0DgnJzhQADAQAAiXNlY3AyNTZrMaED6Oeo1IGkFHaiCJwMMoYvMLnk-kssqhU5RMsA3lO3MsuDdGNwgkA3g3VkcIJAOYV3YWt1MgU --filternode=/ip4/172.18.47.141/tcp/16439/p2p/16Uiu2HAmUL9pMnARBy3dPdwXsam9hDZBAbjJbMS2LWA6d2fNQw2J
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.9.171 waku 362f30ceebb456f6ce06a7ec5507347a616535e398edfe8e66a23376b87a2d9d
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 362f30ceebb4. Setting up logs at ./log/docker/node2_2024-12-04_11-44-46__b8e58e4d-8a9f-4015-a11f-13b4a7d16496__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 43952
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:43952/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:43952/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.9.171/tcp/43953/p2p/16Uiu2HAm68RN4GV15QBFm1CHsEej8MV6NWFbbMp3F5wwzNNu5G1Q","/ip4/172.18.9.171/tcp/43954/ws/p2p/16Uiu2HAm68RN4GV15QBFm1CHsEej8MV6NWFbbMp3F5wwzNNu5G1Q"],"enrUri":"enr:-L24QOqV-OekePN1XTW0Za91K3F9LheazGzKoujFWgmzxktTRA6UV5lUegds5QXObOh61l2luaDy5AyEExTV9jAI4K4CgmlkgnY0gmlwhKwSCauKbXVsdGlhZGRyc5YACASsEgmrBquxAAoErBIJqwarst0DgnJzhQADAQAAiXNlY3AyNTZrMaECnwUn6Z33Ry2bRDuGKExi53eAIccwE1ZxZ_lNoeK3RvODdGNwgquxg3VkcIKrs4V3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:43952/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.47.141/tcp/16439/p2p/16Uiu2HAmUL9pMnARBy3dPdwXsam9hDZBAbjJbMS2LWA6d2fNQw2J"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:16438/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:43952/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "347b8bd1-74ba-48f3-b892-4ba3a751de1c", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"347b8bd1-74ba-48f3-b892-4ba3a751de1c","statusDesc":"OK"}'
[35mDEBUG   [0m tests.filter.test_get_messages:test_get_messages.py:48 Running test with Ephemeral True
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:16438/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "ephemeral": true}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:43952/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1733312706884242176,"ephemeral":true}]'
[35mDEBUG   [0m tests.filter.test_get_messages:test_get_messages.py:48 Running test with Ephemeral False
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:16438/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "ephemeral": false}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:43952/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1733312707005090816,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id c4d259a7f113
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 362f30ceebb4
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container c4d259a7f113. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.