[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_version with id: 2024-12-04_11-44-46__a4902332-3991-4960-8fa8-37a714a717bd
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__a4902332-3991-4960-8fa8-37a714a717bd__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.36.247
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['58627', '58628', '58629', '58630', '58631']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 58627:58627 -p 58628:58628 -p 58629:58629 -p 58630:58630 -p 58631:58631 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=58629 --rest-port=58627 --tcp-port=58628 --discv5-udp-port=58630 --rest-address=0.0.0.0 --nat=extip:172.18.36.247 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=e7332fbe5b8068ad52c1fc2d100ebaea8bf0e72f8bd39ef4f4fb7027fc5ba5a5 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=58631 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.36.247 waku f9ed52a05cfce135f48b36d7bbf4d9eed39b26fbb40631f4a2e6ab9277eefcdd
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID f9ed52a05cfc. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__a4902332-3991-4960-8fa8-37a714a717bd__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 58627
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58627/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58627/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.36.247/tcp/58628/p2p/16Uiu2HAmCFRE79GPVBECMf2tLZwJjcWnaFs6VWaYpemksFAizjMZ","/ip4/172.18.36.247/tcp/58629/ws/p2p/16Uiu2HAmCFRE79GPVBECMf2tLZwJjcWnaFs6VWaYpemksFAizjMZ"],"enrUri":"enr:-L24QEX5qdst1eaVosyQlFKebl9KJao76pW2vaj51LnFT58yVqfIlTuzXF1LdcwEW_qeTiK4R13D83FEfMNhRy3fC6cCgmlkgnY0gmlwhKwSJPeKbXVsdGlhZGRyc5YACASsEiT3BuUEAAoErBIk9wblBd0DgnJzhQADAQAAiXNlY3AyNTZrMaEC-fYwKce6Eib-MgQMCyRHowpoeh7QFWWsWWgGbPFVvSiDdGNwguUEg3VkcILlBoV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-46__a4902332-3991-4960-8fa8-37a714a717bd__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.154.191
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['36632', '36633', '36634', '36635', '36636']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 36632:36632 -p 36633:36633 -p 36634:36634 -p 36635:36635 -p 36636:36636 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=36634 --rest-port=36632 --tcp-port=36633 --discv5-udp-port=36635 --rest-address=0.0.0.0 --nat=extip:172.18.154.191 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=3c8784baab61071da6bdbcd24b9400cecda53b86ee2fba528dd3f2cf1f0f4ad0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=36636 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QEX5qdst1eaVosyQlFKebl9KJao76pW2vaj51LnFT58yVqfIlTuzXF1LdcwEW_qeTiK4R13D83FEfMNhRy3fC6cCgmlkgnY0gmlwhKwSJPeKbXVsdGlhZGRyc5YACASsEiT3BuUEAAoErBIk9wblBd0DgnJzhQADAQAAiXNlY3AyNTZrMaEC-fYwKce6Eib-MgQMCyRHowpoeh7QFWWsWWgGbPFVvSiDdGNwguUEg3VkcILlBoV3YWt1MgU --filternode=/ip4/172.18.36.247/tcp/58628/p2p/16Uiu2HAmCFRE79GPVBECMf2tLZwJjcWnaFs6VWaYpemksFAizjMZ
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.154.191 waku bcd702ac0493480cd5c33a0ba8b287e5b3ab8111de537b8ac185d7e7e6e22425
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID bcd702ac0493. Setting up logs at ./log/docker/node2_2024-12-04_11-44-46__a4902332-3991-4960-8fa8-37a714a717bd__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 36632
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36632/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36632/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.154.191/tcp/36633/p2p/16Uiu2HAmGbEyU5GPfmURwa1nPDG88WPzh8K3mNY99hzcv7jEmjC7","/ip4/172.18.154.191/tcp/36634/ws/p2p/16Uiu2HAmGbEyU5GPfmURwa1nPDG88WPzh8K3mNY99hzcv7jEmjC7"],"enrUri":"enr:-L24QHgoiZxj-zQsHJa9nFqB_-iLqBMKlCQ9591AgEUhL6IbJ_ydVnNEi9RnWhxxv86a-IBbNsJqsLS9AfM5_UyP5fsCgmlkgnY0gmlwhKwSmr-KbXVsdGlhZGRyc5YACASsEpq_Bo8ZAAoErBKavwaPGt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDOnj1qF5Hy81M8r0LutcZg1fUpQDVBFV4oF065FvZHlyDdGNwgo8Zg3VkcIKPG4V3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36632/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.36.247/tcp/58628/p2p/16Uiu2HAmCFRE79GPVBECMf2tLZwJjcWnaFs6VWaYpemksFAizjMZ"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58627/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36632/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "87b9c336-5b07-4836-a978-226c3173055e", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"87b9c336-5b07-4836-a978-226c3173055e","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58627/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "version": 10}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36632/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":10,"timestamp":1733312703883378176,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id f9ed52a05cfc
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id bcd702ac0493
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container f9ed52a05cfc. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.